proyectofinal/MisCosas/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index),
    path('info', views.info),
    path('logout', views.logout_view),
    path('register', views.register),
    path('youtube', views.youtubeal),
    path('youtube/<str:id>', views.youtubechannel),
    path('reddit', views.reddital),
    path('usuarios', views.usuarios),
    path('youtube/<str:canal_id>/<str:item_id>', views.youtubevid),
    path('reddit/<str:id>', views.subreddit),
    path('reddit/<str:subreddit_id>/<str:item_id>', views.redditnot),
    path('letras', views.letras),
    path('oscuro', views.oscuro),
    path('vote/<str:item_id>', views.vote),
    path('comment/<str:item_id>', views.comment),
    path('alimentadores', views.alimentadores),
    path('delete', views.delete),
    path('loggedIn', views.loggedIn),
    path('<str:username>', views.user),
    path('i18n/', include('django.conf.urls.i18n')),

]

proyectofinal/proyectofinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView as login
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404
urlpatterns = [
    path('admin/', admin.site.urls),
    path('miscosas/', include('MisCosas.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'MisCosas.views.pag_404_not_found'

proyectofinal/MisCosas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
class Alimentador(models.Model):
    id = models.CharField(max_length=64, primary_key=True)
    title = models.CharField(max_length=64, null=True)
    link = models.CharField(max_length=64, null=True)
    num_items = models.IntegerField(default=0)
    puntuacion = models.IntegerField(default=0)
    selected = models.BooleanField(default = True)
    tipo = models.CharField(max_length = 64, null=True)
    def __str__(self):
        return self.title

class Item(models.Model):
    alimentador = models.ForeignKey(Alimentador, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=64, null=True)
    link = models.CharField(max_length=64, null=True)
    id = models.CharField(max_length=64, primary_key=True)
    description = models.CharField(max_length=256, null=True)
    positivos = models.IntegerField(default=0)
    negativos = models.IntegerField(default=0)
    puntuacion = models.IntegerField(default=0)


    def __str__(self):
        return self.title

class Vote(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    item = models.ForeignKey(Item,on_delete=models.CASCADE)
    voto = models.IntegerField(default=0)

    def __str__(self):
        return 'El user que ha votado ' + self.user.username + ' Con items: ' + self.item.title
class Image(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, null = True)
    photo = models.ImageField(upload_to = 'media', default="nopic.jpg")

class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    item = models.ForeignKey(Item,on_delete=models.CASCADE)
    title = models.CharField(max_length = 50, null = True)
    comment = models.CharField(max_length=250, null = True)
    date= models.DateTimeField(default = timezone.now)
    photourl = models.URLField(null = True)


    def __str__(self):
        return self.comment

class Style(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    oscuro =  models.BooleanField(default = False)
    letra = models.CharField(max_length = 2, default = 'M')

proyectofinal/MisCosas/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Alimentador, Image

class UploadImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ('photo',)

proyectofinal/MisCosas/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader, Context, RequestContext
from django.views.decorators.csrf import csrf_exempt
import urllib.request
from .ytchannel import YTChannel
from .redditnotice import Reddit
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as do_login
from .models import Alimentador, Item, Vote, Comment, Image, Style
from .forms import UploadImageForm
from django.contrib.auth.models import User
from django.conf import settings
from django.template.loader import get_template
import json
from django.core import serializers
from django.views.defaults import page_not_found
@csrf_exempt

# ...

def index(request):
    # Creamos el formulario de autenticación vacío
    if request.method == 'GET':
        format = request.GET.get('format')
        if format:
            if format == 'xml':
                return HttpResponse(docxml(request.user), status=200, content_type="application/xml")
            else:
                return HttpResponse(docjson(request.user), status=200, content_type="application/json")

        Alimentadores = Alimentador.objects.all()
        top10 =Item.objects.order_by('-puntuacion')[:10]
        itemvoted = []
        if request.user.is_authenticated:
            imagen = Image.objects.get(user = request.user).photo
            votes = Vote.objects.filter(user = request.user)
            for vote in votes:
                itemvoted.append(vote.item)
            top5 = votes[:5]
        else:
            imagen = Image.objects.none()
            votes = Vote.objects.none()
            top5 = votes[:]
        if request.user.is_authenticated:
            style = Style.objects.get(user = request.user)
        else:
            style = Style.objects.none()

        # Si llegamos al final renderizamos el formulario
        return render(request, "pages/index.html", {'alimentadores': Alimentadores, 'imagen': imagen,
        'style': style, 'votes':votes, 'top10': top10 , 'itemvoted': itemvoted, 'top5': top5})

def info(request):
    user = request.user
    try:
        imagen = Image.objects.get(user=user).photo
    except:
        imagen = Image.objects.none()
    if request.user.is_authenticated:
        style = Style.objects.get(user = request.user)
    else:
        style = Style.objects.none()
    return render(request, "pages/info.html", {'imagen': imagen,
    'style': style})
def docxml(user):
    template = get_template("index.xml")
    alimentadores = Alimentador.objects.filter(selected=True)
    top10 = Item.objects.order_by('-puntuacion')[:10]
    if user.is_authenticated:
        top5 = Vote.objects.filter(user=user)[:5]
        c = {"user":user,"alimentadores" : alimentadores, "top10" : top10, "top5":top5}
    else:
        c = {"alimentadores" : alimentadores, "top10" : top10}
    respuesta = template.render(c)
    return HttpResponse(respuesta, status=200, content_type="application/xml")

def docjson(user):
    all = [*Alimentador.objects.filter(selected=True), *Item.objects.order_by('-puntuacion')[:10]]
    indexjson = serializers.serialize('json', all)
    if user.is_authenticated:
        all = [*Alimentador.objects.filter(selected=True), *Item.objects.order_by('-puntuacion')[:10], *Vote.objects.filter(user=user)[:5]]
        indexjson = serializers.serialize('json', all)
    return indexjson


def alimentadores(request):
    Alimentadores = Alimentador.objects.all()
    user =  request.user
    try:
        imagen = Image.objects.get(user=user).photo
        print(imagen)
    except:
        imagen = Image.objects.none()
    if request.user.is_authenticated:
        style = Style.objects.get(user = request.user)
    else:
        style = Style.objects.none()
    content = {'user': request.user, 'alimentadores': Alimentadores, 'imagen': imagen, 'style': style, }
    return render(request, 'pages/alimentadores.html', content)

def youtubeal(request):
    Alimentadores = Alimentador.objects.all()
    user = request.user
    if request.method == 'POST':
        id = request.POST['id']
        try:
            channel = Alimentador.objects.get(id=id)
            if id != '':
                xml = "https://www.youtube.com/feeds/videos.xml?channel_id=" + id
                xmlStream = urllib.request.urlopen(xml)
                canal = YTChannel(xmlStream)
                channel = Alimentador.objects.get(id=id)

                items = Item.objects.filter(alimentador=channel)
                channel.num_items = len(items)
                channel.selected = True;
                channel.save()
        except:

            if id != '':
                xml = "https://www.youtube.com/feeds/videos.xml?channel_id=" + id
                xmlStream = urllib.request.urlopen(xml)
                canal = YTChannel(xmlStream)
                channel = Alimentador.objects.get(id=id)

                items = Item.objects.filter(alimentador=channel)
                channel.num_items = len(items)
                channel.selected = True;
                channel.save()

    return redirect('/miscosas/youtube/' + id)

def youtubechannel(request, id):
        user = request.user
        try:
            imagen = Image.objects.get(user=user).photo
        except:
            imagen = Image.objects.none()
        if request.user.is_authenticated:
            style = Style.objects.get(user = request.user)
        else:
            style = Style.objects.none()

        channel = Alimentador.objects.get(id=id)

        content = {'channel': channel, 'videos': Item.objects.filter(alimentador=channel).order_by('title'),
                        'user': request.user, 'imagen': imagen, 'style': style}
        return render(request, 'pages/youtube.html', content)

def youtubevid(request, canal_id, item_id):
    Alimentadores = Alimentador.objects.all()
    user = request.user
    try:
        imagen = Image.objects.get(user=user).photo
    except:
        imagen = Image.objects.none()
    if request.user.is_authenticated:
        style = Style.objects.get(user = request.user)
    else:
        style = Style.objects.none()
    video = get_object_or_404(Item, id=item_id)
    embeddedvid = "https://www.youtube.com/embed/" + item_id
    try:
        Voto = Vote.objects.filter(user= request.user).get(item = video)
    except:
        Voto = Vote.objects.none()
    Comments = Comment.objects.filter(item=video)


    content = {'video': video, 'embeddedvid': embeddedvid, 'alimentadores': Alimentadores,
                'voto': Voto, 'Comments': Comments, 'imagen': imagen, 'style': style}



    return render(request, 'pages/video.html', content)

def pag_404_not_found(request, exception):
   response = page_not_found(request, "pages/404.html")
   response.status_code=404
   return response

def reddital(request):
    if request.method == 'POST':
        id = request.POST['id']
        try:
            subreddit = Alimentador.objects.get(id=id)
            if id != '':
                xml = "http://www.reddit.com/r/" + id + ".rss"
                xmlStream = urllib.request.urlopen(xml)
                hilo = Reddit(xmlStream)
                subreddit = Alimentador.objects.get(id=id)

                items = Item.objects.filter(alimentador=subreddit)
                subreddit.num_items = len(items)
                subreddit.selected = True;
                subreddit.save()
        except:

            if id != '':
                xml = "http://www.reddit.com/r/" + id + ".rss"
                xmlStream = urllib.request.urlopen(xml)
                hilo = Reddit(xmlStream)
                subreddit = Alimentador.objects.get(id=id)

                items = Item.objects.filter(alimentador=subreddit)
                subreddit.num_items = len(items)
                subreddit.selected = True;
                subreddit.save()




    return redirect('/miscosas/reddit/' + id)



def subreddit(request, id):
    Alimentadores = Alimentador.objects.all()
    user = request.user
    try:
        imagen = Image.objects.get(user=user).photo
    except:
        imagen = Image.objects.none()
    if request.user.is_authenticated:
        style = Style.objects.get(user = request.user)
    else:
        style = Style.objects.none()
    subreddit = Alimentador.objects.get(id=id)

    content = {'subreddit': subreddit, 'notices': Item.objects.filter(alimentador=subreddit).order_by('title'),
                        'user': request.user, 'alimentadores': Alimentadores, 'imagen': imagen, 'style':style}

    return render(request, 'pages/reddit.html', content)


def redditnot(request, subreddit_id, item_id):
    Alimentadores = Alimentador.objects.all()
    user = request.user
    try:
        imagen = Image.objects.get(user=user).photo
    except:
        imagen = Image.objects.none()
    if request.user.is_authenticated:
        style = Style.objects.get(user = request.user)
    else:
        style = Style.objects.none()
    notice = get_object_or_404(Item, id=item_id)
    try:
        Voto = Vote.objects.filter(user= request.user).get(item = notice)
    except:
        Voto = Vote.objects.none()
    Comments = Comment.objects.filter(item=notice)


    content = {'notice': notice, 'alimentadores': Alimentadores,
                'voto': Voto, 'Comments': Comments, 'imagen': imagen, 'style': style}
    return render(request, 'pages/notice.html', content)

def delete(request):
    if request.method == 'POST':
        id = request.POST['id']
        channel = Alimentador.objects.get(id=id)
        if(channel.selected == True):
            channel.selected = False
        else:
            channel.selected = True

        channel.save()
        return redirect('/miscosas')




    return render(request, 'pages/youtube.html', content)

def usuarios(request):

proyectofinal/MisCosas/templates/pages/alimentadores.html
{% extends 'pages/base.html' %}
{% load i18n %}

  {% block youtube %}
  <h2>{% trans "Alimentadores" %}</h2>
  <ul>
    {% for aliment in alimentadores %}
    <br>Link {{aliment}}: <a href='{{aliment.link}}'>{{ aliment.link }}</a><br>

      {% if aliment.tipo == 'yt' %}
      {% if style.oscuro == True %}
      <a href="/miscosas/youtube/{{aliment.id}}"class="list-group-item list-group-item-action list-group-item-dark">
      {% else %}
      <a href="/miscosas/youtube/{{aliment.id}}"class="list-group-item list-group-item-action list-group-item-primary">
      {% endif %}

      {% else %}
      {% if style.oscuro == True %}
      <a href="/miscosas/reddit/{{aliment.id}}"class="list-group-item list-group-item-action list-group-item-dark">
      {% else %}
      <a href="/miscosas/reddit/{{aliment.id}}"class="list-group-item list-group-item-action list-group-item-primary">
      {% endif %}
      {% endif %}
          {% trans "Canal" %}: {{ aliment }}
          <br>Num items: {{aliment.num_items}} .
          <br>{% trans "Puntuacion" %}: {{aliment.puntuacion}}  </a>


    {% endfor %}
  {% endblock %}

proyectofinal/MisCosas/templates/pages/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="es" >
  <head>
    <meta charset="utf-8" />
    <title>MisCosas</title>
      <link rel="icon" type="image/png" href="{% static "MisCosas/icon.png" %}">
    <link rel="stylesheet" href="{% static "MisCosas/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "MisCosas/main.css" %}">
    {% if style.oscuro %}
      <link rel="stylesheet" href="{% static "MisCosas/oscuro.css" %}">
    {% endif %}
    {% if style.letra == 'P' %}
      <link rel="stylesheet" href="{% static "MisCosas/fuentepequeña.css" %}">
    {% endif %}
    {% if style.letra == 'G' %}
      <link rel="stylesheet" href="{% static "MisCosas/fuentegrande.css" %}">
    {% endif %}
  </head>
  <body>
    <div class = "jumbotron" id = "encabezado">
      <h1> {% trans "Mis Cosas" %} </h1>
      <div class="row">
       <div class="column">
         <img src="{% static "MisCosas/logo.png" %}" alt="My image" style="width:220px;height:120px;">
       </div>
         <div id = "login">
           {% if user.is_authenticated %}
            <img src="{{imagen.url}}" alt "My Profile image" style="width:100px;height:100px;">
             <h3> {% trans "Bienvenido" %} {{user.username}}</h3>

             <a href="/miscosas/logout">{%trans "Cerrar sesión" %}</a>
          {% else %}
            <h3>{% trans "Iniciar sesión" %}</h3>

            <form method="POST" action="/miscosas/loggedIn">
              {% csrf_token %}
                <div class = "form-group">
                <td>{% trans "Usuario" %}</td>

                      <td><input type="text" name="username" value="{{ form.username1 }}" required = True></td>
                  </tr>
                  <tr>

                    <br>  <td>{% trans "Contraseña" %}</td>
                      <td><input type="password" name="password" value="{{ form.password }}" required = True></td>
                  </tr>

                <br>  <button type="submit" name="id" >{% trans "Iniciar sesión" %}</button>
              </div>

            </form>

          <a href="/miscosas/register">{% trans "Registrar usuario" %}</a>

          {% endif %}

         </div>
       </div>
     </div>
    </div>

    <div id="navegador" tabindex="1">
      <ul>
        <li><a href="/miscosas/alimentadores">{% trans "Alimentadores" %}</a></li>
        <li><a href="/miscosas/usuarios">{% trans "Usuarios" %}</a></li>
        <li><a href="/miscosas/{{user.username}}">{% trans "Mi Perfil" %}</a></li>
        <li><a href="/miscosas">{% trans "Inicio" %}</a></li>
        <li><a href="/miscosas/info">{% trans "Información" %}</a></li>
      </ul>
    </div>
  <div class= row>
    <div id = "alimentadores">
      {% block Alimentadores %}

         {% endblock %}
    </div>

          <div id = "videos">
            {% block youtube %}{% endblock %}
            <br><h2>{% trans "Fuentes" %}</h2>
         {% trans "Esta web recoge datos de canales y vídeos de" %} <a href="https://www.youtube.com">Youtube</a> {% trans "así como hilos de" %} <a href="https://www.reddit.com">Reddit </a>
          </div>


         <div id="youtube">
           {% block index %}

              {% endblock %}

  <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
      <input name="next" type="hidden" value="{{ redirect_to }}">
      <select name="language">
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% get_language_info_list for LANGUAGES as languages %}
          {% for language in languages %}
              <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                  {{ language.name_local }} ({{ language.code }})
              </option>
          {% endfor %}
      </select>
      <input type="submit" value="Go">
  </form>


          <br> <h2></h2>
         </div>


    </body>
  </html>
</div>

proyectofinal/MisCosas/templates/pages/index.html
{% extends 'pages/base.html' %}
{% load i18n %}

  {% block Alimentadores %}
  <h2>{% trans "Alimentadores" %}</h2>
  <ul>


    {% for aliment in alimentadores %}

     {% if aliment.selected %}
      <li>{% trans "Canal" %}:{{ aliment }}
        <br>Link: <a href='{{aliment.link}}'>{{ aliment }}</a>
        <br>Num items: {{aliment.num_items}} .
        <br>{% trans "Puntuacion" %}: {{aliment.puntuacion}}
        {% if aliment.tipo == 'yt' %}
          <form method="POST" action="/miscosas/youtube">
            {% csrf_token %}
            <input type="hidden" name="id" value = "{{aliment.id}}">
            <input type="submit" name="Alimentador" value="Ir">
          </form>
           <form method="POST" action="/miscosas/delete">
             {% csrf_token %}
             <input type="hidden" name="id" value = "{{aliment.id}}">
             <input type="submit" name="Alimentador" value="Borrar">
           </form>
         {% else %}
         <form method="POST" action="/miscosas/reddit">
           {% csrf_token %}
           <input type="hidden" name="id" value = "{{aliment.id}}">
           <input type="submit" name="Alimentador" value="Ir">
         </form>
          <form method="POST" action="/miscosas/delete">
            {% csrf_token %}
            <input type="hidden" name="id" value = "{{aliment.id}}">
            <input type="submit" name="Alimentador" value="Borrar">
          </form>
       </li>
       {% endif %}
      {% endif %}
    {% endfor %}
  </ul>
  <br><b> {% trans "Descargar la página en formato" %} </b>
          <form action="" method='GET'>
         <input type='submit' name='format' value='xml'>
         <input type='submit' name='format' value='json'>
          </form>
  {% endblock %}
  {% block index %}
  <form method="POST" action="/miscosas/youtube">
    {% csrf_token %}
    <br>{% trans "Canal de Youtube" %}: <input type="text" name="id" required = True>
    <input type="submit" name="Alimentador" value="Ver">
  </form>
  <form method="POST" action="/miscosas/reddit">
    {% csrf_token %}
    <br>Subreddit: <input type="text" name="id" required = True>
    <input type="submit" name="Alimentador" value="Ver">
  </form>
 <br> <h2>{% trans "Top10 Items Votados" %}</h2>
 {% for item in top10 %}
  {%  if item.alimentador.tipo == 'yt' %}
    <br> <a href='/miscosas/youtube/{{item.alimentador.id}}/{{item.id}}'>{{item}}
  {% else %}
    <br> <a href='/miscosas/reddit/{{item.alimentador.id}}/{{item.id}}'>{{item}}
  {% endif %}
<br>  <a href='{{item.link}}'>{{item.link}}</a>
<br>  <span class="badge badge-success badge-pill">{% trans "Positivos" %}: {{item.positivos}}</span>
      <span class="badge badge-danger badge-pill">{% trans "Negativos" %}: {{item.negativos}}</span>
   {% if user.is_authenticated %}

   <form method="POST" action="/miscosas/vote/{{item.id}}">
       {% csrf_token %}

           {% if item in itemvoted %}
             {% for vote in votes %}

               {% if vote.item == item %}

                 {% if vote.voto == 1 %}

                   <td><input type="submit" name="vote" value="like" id = 'like' disabled =  True></td>

                 {% else %}
                   <td><input type="submit" name="vote" value="like"></td>
                 {% endif %}
                 {% if vote.voto == -1 %}

                   <td ><input type="submit" name="vote" value="dislike" id ='dislike' disabled = True></td>
                 {% else %}

                   <td><input type="submit" name="vote" value="dislike"></td>
                 {% endif %}


               {% endif %}

               {% endfor %}

           {% else %}
               <td><input type="submit" name="vote" value="like"></td>
               <td><input type="submit" name="vote" value="dislike"></td>
           {% endif %}
               </form>

     {% endif %}

 {% endfor %}

   {% if user.is_authenticated %}
     <br> <h2>{% trans "Last5 ItemsVotados" %}</h2>
   {% for vote in top5 %}

   {%  if vote.item.alimentador.tipo == 'yt' %}
     <br> <a href='/miscosas/youtube/{{vote.item.alimentador.id}}/{{vote.item.id}}'>{{vote.item}}
   {% else %}
     <br> <a href='/miscosas/reddit/{{vote.item.alimentador.id}}/{{vote.item.id}}'>{{vote.item}}
   {% endif %}
 <br>  <a href='{{vote.item.link}}'>{{vote.item.link}}</a>
 <br>  <span class="badge badge-success badge-pill">{% trans "Positivos" %}: {{vote.item.positivos}}</span>
  <span class="badge badge-danger badge-pill">{% trans "Negativos" %}: {{vote.item.negativos}}</span>
       <form method="POST" action="/miscosas/vote/{{vote.item.id}}">
           {% csrf_token %}

                   {% if vote.user == user %}

                     {% if vote.voto == 1 %}

                       <td><input type="submit" name="vote" value="like" id = 'like' disabled =  True></td>

                     {% else %}
                       <td><input type="submit" name="vote" value="like"></td>
                     {% endif %}
                     {% if vote.voto == -1 %}

                       <td ><input type="submit" name="vote" value="dislike" id ='dislike' disabled = True></td>
                     {% else %}

                       <td><input type="submit" name="vote" value="dislike"></td>
                     {% endif %}


               {% else %}
                   <td><input type="submit" name="vote" value="like"></td>
                   <td><input type="submit" name="vote" value="dislike"></td>
               {% endif %}
                   </form>
         {% endfor %}
         {% endif %}
  {% endblock %}

proyectofinal/MisCosas/templates/pages/info.html
{% extends 'pages/base.html' %}
{% load i18n %}

{% block youtube %}
  <h3>{% trans "Esta es la página de MisCosas" %}</h3>
    <br><h2>{%trans "Creada por Luis Álvarez Jerónimo" %}</h1>
<br>{% trans "La página utiliza datos de Youtube y Reddit llamando a canales e hilos concretos para mostrar sus datos." %}
<br>{% trans "Existe un sistema de usuarios que, al registrarte te permiten votar y comentar los items ofrecidos por los Alimentadores" %}
{% endblock %}

proyectofinal/MisCosas/templates/pages/notice.html
{% extends 'pages/base.html' %}
{% load i18n %}

{% block youtube %}
    <h1> {{notice}} </h1>
    <li>
      <br>Link: <a href='{{notice.link}}'>{{notice.link}}</a>
      <br>
      <div id  = 'RedditPost'>
        {% trans "Descripción" %}:
        <br>{{notice.description|safe}}
      </div>
      <br> Subreddit: <a href='/miscosas/reddit/{{notice.alimentador.id}}'>{{notice.alimentador.title}}</a>
      <br>Link: <a href='{{notice.alimentador.link}}'>{{notice.link}}</a>
      <br>Num items: {{notice.alimentador.num_items}} .
      <br>{% trans "Puntuacion" %}: {{notice.alimentador.puntuacion}}

        <div class = "caja">
            {% trans "Comentarios" %}
            {% for comment in Comments %}
           <br>{{comment.user}}: {{comment.date}} {{comment.title}}
              <br> {{comment.comment}}
            {% endfor %}
        </div>
         {% if user.is_authenticated %}
          <form method="POST" action="/miscosas/vote/{{notice.id}}">
            {% csrf_token %}
            {% if voto.voto == 1 %}

              <td><input type="submit" name="vote" value="like" id = 'like' disabled =  True></td>

            {% else %}
              <td><input type="submit" name="vote" value="like"></td>
            {% endif %}
            {% if voto.voto == -1 %}

              <td ><input type="submit" name="vote" value="dislike" id ='dislike' disabled = True></td>
            {% else %}

              <td><input type="submit" name="vote" value="dislike"></td>
            {% endif %}

          </form>
          <form method="POST" action="/miscosas/comment/{{notice.id}}">
            {% csrf_token %}
            {% trans "Título" %}
            <br>  <td><input type="text" name="Title" value="{{ form.title }}"></td>
            <br> {% trans "Comentario" %}
            <br> <input type="text" name="Comment" value="{{ form.comment }}">
            <br> {% trans "Imagen" %}
            <br> <input type="text" name="Photo" value="{{ form.photo }}">
              <button type="submit" name="id" >{% trans "Comentario" %}</button>
          </form>

        

        {% endif %}






{% endblock %}

proyectofinal/MisCosas/templates/pages/register.html
{% extends 'pages/base.html' %}
{% block youtube %}
<h2>Registrar usuario</h2>

<form method="POST">
    {{ form.as_p }}
    {% csrf_token %}

    <button type="submit">{% trans "Registrar"}</button>
</form>

<hr />


{% endblock %}

proyectofinal/MisCosas/templates/pages/usuarios.html
{% extends 'pages/base.html' %}
{% load i18n %}

  {% block youtube %}
      <h2>{% trans "Usuarios de MisCosasApp" %}</h2>
      <div class="list-group">
        {% for imagen in imagenes %}
          <li class="media">
        {% if style.oscuro == True %}
        <a href="/miscosas/{{ imagen.user.username }}"class="list-group-item list-group-item-action list-group-item-dark">
        {% else %}
        <a href="/miscosas/{{ imagen.user.username }}"class="list-group-item list-group-item-action list-group-item-primary">
        {% endif %}
           <img src="{{ imagen.photo.url }}" alt="My Profile Image" width="100" height="80">
           <div class= "media-body">
              <h5>{% trans "Usuario" %}:
              {{ imagen.user.username }} </h5>
              {% trans "Items votados" %}:  <span class="badge badge-primary badge-pill">{{ imagen.user.vote_set.count }}</span>
              {% trans "Items comentados: "%}  <span class="badge badge-primary badge-pill">{{ imagen.user.comment_set.count }}</span>

            </div>
            </a>
          </li>

        {% endfor %}
      </div>


  {% endblock %}